import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { TouchTextInput } from './components/touchKeyboard/TouchTextInput';
import { AdcPreset, AdcSnapshot, ADC_WRITABLE, AdcControlId, adcCommandsBusy, adcDisplayByte, adcIdentificationMessage, adcWriteMessage, decodeAdcControl, encodeAdcControl, encodeVco, ReleasedDraft, validateClampWindow } from './rnseAdcModel';
import './rnseAdcPanel.css';

type Api = <T>(path:string, init?:RequestInit)=>Promise<T>;
interface Props { api:Api; pin?:string; onTestPattern:()=>void; }
type Page='rgb'|'timing'|'sync'|'dump';
const headers=(pin:string)=>({'Content-Type':'application/json','X-Hudiy-Management':'1',...(pin?{'X-Hudiy-Pin':pin}:{})});
const hex=(n:number|null|undefined)=>n==null?'—':`0x${n.toString(16).padStart(2,'0').toUpperCase()}`;
const caps:Record<AdcControlId,number>={gainR:255,gainG:255,gainB:255,offsetR:127,offsetG:127,offsetB:127,phase:31,vcoRange:3,vcoCurrent:7,clampPlacement:255,clampDuration:255,preCoast:255,postCoast:255,threshold:255};
const initial:Record<AdcControlId,number>={gainR:112,gainG:112,gainB:112,offsetR:63,offsetG:63,offsetB:63,phase:16,vcoRange:0,vcoCurrent:6,clampPlacement:22,clampDuration:47,preCoast:6,postCoast:6,threshold:32};
const regFor=(id:AdcControlId)=>encodeAdcControl(id,0).register;

function Slider({id,label,value,disabled,detail,status,syncToken,onCommit}:{id:AdcControlId;label:string;value:number;disabled:boolean;detail?:string;status:string;syncToken:number;onCommit:(v:number)=>void}){
 const [draft,setDraft]=useState(value); const gesturing=useRef(false); const values=useRef(new ReleasedDraft(value));
 useEffect(()=>{if(!gesturing.current){values.current.sync(value);setDraft(value);}},[value,syncToken]);
 const change=(v:number)=>{values.current.change(v);setDraft(v);};
 const release=()=>{gesturing.current=false;const v=values.current.release();if(v!==null)onCommit(v);};
 const step=(n:number)=>{change(Math.max(0,Math.min(caps[id],draft+n)));release();};
 return <div className="adc-control"><div className="adc-control-head"><label htmlFor={`adc-${id}`}>{label}</label><output htmlFor={`adc-${id}`}>{draft}{detail?` · ${detail}`:''}</output></div><div className="adc-range"><button type="button" aria-label={`Decrease ${label}`} disabled={disabled||draft<=0} onClick={()=>step(-1)}>−</button><input id={`adc-${id}`} type="range" min="0" max={caps[id]} step="1" value={draft} disabled={disabled} aria-label={label} onPointerDown={e=>{gesturing.current=true;e.currentTarget.setPointerCapture(e.pointerId);}} onChange={e=>change(Number(e.target.value))} onPointerUp={release} onPointerCancel={()=>{gesturing.current=false;setDraft(values.current.cancel());}} onKeyDown={()=>{gesturing.current=true;}} onKeyUp={release} onBlur={release}/><button type="button" aria-label={`Increase ${label}`} disabled={disabled||draft>=caps[id]} onClick={()=>step(1)}>+</button></div><small className="adc-control-status">{status}</small></div>;
}

export function RnseAdcPanel({api,pin='',onTestPattern}:Props){
 const [page,setPage]=useState<Page>('rgb'),[snapshot,setSnapshot]=useState<AdcSnapshot|null>(null),[presets,setPresets]=useState<Record<string,AdcPreset>>({}),[presetName,setPresetName]=useState(''),[selected,setSelected]=useState(''),[linked,setLinked]=useState(true);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[syncVersion,setSyncVersion]=useState(0);
 const busyRef=useRef(false),requestEpoch=useRef(0),alive=useRef(false),snapshotRef=useRef<AdcSnapshot|null>(null);
 const refresh=useCallback(async()=>{if(busyRef.current)return;const epoch=requestEpoch.current;try{const next=await api<AdcSnapshot>('/rnse-adc');if(alive.current&&!busyRef.current&&epoch===requestEpoch.current){snapshotRef.current=next;setSnapshot(next);}}catch(e){if(alive.current&&!busyRef.current&&epoch===requestEpoch.current&&!snapshotRef.current)setError(e instanceof Error?e.message:'ADC controls unavailable.');}finally{if(alive.current)setLoading(false);}},[api]);
 const refreshPresets=useCallback(async()=>{try{const result=await api<{presets?:Record<string,AdcPreset>}>('/rnse-adc/presets');setPresets(result.presets||{});}catch{/* Preset support can arrive independently of live control. */}},[api]);
 useEffect(()=>{alive.current=true;void refresh();void refreshPresets();const timer=window.setInterval(()=>void refresh(),500);return()=>{alive.current=false;window.clearInterval(timer);};},[refresh,refreshPresets]);
 const liveValues=useMemo(()=>{const values={...initial}; for(const id of Object.keys(caps) as AdcControlId[]){const v=adcDisplayByte(snapshot,regFor(id));if(v!=null)values[id]=decodeAdcControl(id,v);}return values;},[snapshot]);
 const request=async(path:string,body?:unknown)=>{if(busyRef.current||!snapshotRef.current||adcCommandsBusy(snapshotRef.current))return;busyRef.current=true;requestEpoch.current++;setBusy(true);setSyncVersion(v=>v+1);setError('');setNotice('');try{const next=await api<AdcSnapshot>(path,{method:'POST',headers:headers(pin),body:JSON.stringify(body||{})});if(!alive.current)return;snapshotRef.current=next;setSnapshot(next);if(next.command_error)setError(next.command_error);else if(Object.values(next.writes||{}).some(write=>write.state==='queue_failed'||write.state==='not_sent'))setError('One or more register writes could not be sent. Check each slider status.');else if(path.endsWith('/dump'))setNotice('Dump requested; waiting for all register frames.');else if(path.endsWith('/revert'))setNotice('Revert request sent; check each register status.');else setNotice('Request sent; check each register status for readback.');}catch(e){if(alive.current)setError(e instanceof Error?e.message:'ADC request failed.');}finally{busyRef.current=false;if(alive.current)setBusy(false);}};
 const write=async(values:AdcPreset)=>request('/rnse-adc/write',{values});
 const commit=(id:AdcControlId,value:number)=>{setSyncVersion(v=>v+1);let encoded;try{encoded=encodeAdcControl(id,value);}catch(e){setError(e instanceof Error?e.message:'Invalid ADC value.');return;}if(id==='clampPlacement'&&!validateClampWindow(value,liveValues.clampDuration)){setError('Clamp placement + duration must stay below 110 clocks.');return;}if(id==='clampDuration'&&!validateClampWindow(liveValues.clampPlacement,value)){setError('Clamp placement + duration must stay below 110 clocks.');return;}if(id==='vcoRange'||id==='vcoCurrent'){const range=id==='vcoRange'?value:liveValues.vcoRange,current=id==='vcoCurrent'?value:liveValues.vcoCurrent;void write({'03':encodeVco(range,current)});return;}void write({[encoded.register]:encoded.byte});};
 const runAction=(path:string)=>request(path,{});
 const savePreset=async()=>{const name=presetName.trim();if(!name){setError('Enter a preset name.');return;}if(busyRef.current||!snapshotRef.current)return;busyRef.current=true;requestEpoch.current++;setBusy(true);setError('');try{await api('/rnse-adc/presets',{method:'POST',headers:headers(pin),body:JSON.stringify({name,values:liveValuesToBytes(liveValues)})});if(!alive.current)return;await refreshPresets();setSelected(name);setNotice(`Saved preset “${name}”.`);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not save preset.');}finally{busyRef.current=false;if(alive.current)setBusy(false);}};
 const loadPreset=()=>{const values=presets[selected];if(!values)return;const cleaned:AdcPreset={};for(const [reg,value] of Object.entries(values)){const r=reg.toUpperCase();if(!ADC_WRITABLE.has(r)||!Number.isInteger(value)||value<0||value>255){setError(`Preset contains invalid or locked register ${r}.`);return;}cleaned[r]=value;}if(!Object.keys(cleaned).length){setError('Preset has no writable values.');return;}void write(cleaned);};
 const reg=(address:string)=>snapshot?.registers?.find(r=>r.register.toUpperCase()===address);
 const controlStatus=(id:AdcControlId)=>{const address=regFor(id),message=adcWriteMessage(snapshot,address),reading=reg(address)?.value,write=snapshot?.writes?.[address];if(write&&['queued','pending','queued_unconfirmed','timeout'].includes(write.state))return `Requested ${write.requested} · ${message}`;return message|| (reading==null?'Not read yet':`Dump ${hex(reading)} · no write reply`);};
 const commandActive=adcCommandsBusy(snapshot);
 const disabled=busy||loading||!snapshot||snapshot.inhibited===true||snapshot.radio_active===false||commandActive;
 const chipRegister=reg('1D');
 const identifyAllowed=!!snapshot&&snapshot.dump?.state==='complete'&&chipRegister?.value===0&&!chipRegister.failed;
 return <section className="rnse-adc" aria-label="RNS-E ADC tuning">
   <div className="adc-toolbar"><div className="adc-pages" role="tablist" aria-label="ADC sections">{([['rgb','RGB'],['timing','Timing'],['sync','Sync'],['dump','Dump']] as [Page,string][]).map(([id,label])=><button key={id} role="tab" aria-selected={page===id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</div><div className="adc-actions"><span aria-live="polite">{loading?'Loading…':snapshot?.inhibited?'Paused':snapshot?.radio_active===false?'Radio inactive':`Reply ${snapshot?.reply_id==null?'—':hex(snapshot.reply_id)} · ${snapshot?.state||'Ready'}`}</span>{page==='rgb'&&<label className="adc-link"><input type="checkbox" checked={linked} onChange={e=>setLinked(e.target.checked)}/> Link RGB</label>}<button type="button" disabled={busy} onClick={onTestPattern}>Test image</button></div></div>
   {error&&<p className="adc-error" role="alert">{error}</p>}{notice&&page==='dump'&&<p className="adc-notice" role="status">{notice}</p>}
   {page==='rgb'&&<div className="adc-page-content"><div className="adc-control-grid">{([['gainR','Gain · Red'],['gainG','Gain · Green'],['gainB','Gain · Blue'],['offsetR','Offset · Red'],['offsetG','Offset · Green'],['offsetB','Offset · Blue']] as [AdcControlId,string][]).map(([id,label])=><Slider key={id} id={id} label={label} value={liveValues[id]} disabled={disabled} status={controlStatus(id)} syncToken={syncVersion} detail={id.startsWith('offset')?hex(encodeAdcControl(id,liveValues[id]).byte):undefined} onCommit={v=>{if(linked){const group=id.startsWith('gain')?['gainR','gainG','gainB'] as const:['offsetR','offsetG','offsetB'] as const;const values:AdcPreset={};for(const channel of group){const encoded=encodeAdcControl(channel,v);values[encoded.register]=encoded.byte;}void write(values);}else commit(id,v);}}/>)}</div><p className="adc-hint" title="Offsets set black level; gains set contrast. Higher gain values mean less contrast.">Offsets set black level · Higher gain means less contrast.</p></div>}
   {page==='timing'&&<div className="adc-page-content"><div className="adc-control-grid">{([['phase','Phase'],['vcoRange','VCO range'],['vcoCurrent','Charge pump'],['clampPlacement','Clamp placement'],['clampDuration','Clamp duration']] as [AdcControlId,string][]).map(([id,label])=><Slider key={id} id={id} label={label} value={liveValues[id]} disabled={disabled} status={controlStatus(id)} syncToken={syncVersion} detail={id==='phase'?hex(liveValues.phase<<3):id==='vcoRange'||id==='vcoCurrent'?hex((liveValues.vcoRange<<6)|(liveValues.vcoCurrent<<3)):undefined} onCommit={v=>commit(id,v)}/>)}</div><p className="adc-hint">VCO range and charge pump share one register. Clamp placement + duration must stay below 110 clocks. 480p default: range 0, current 6 (0x30). PLL divider is locked.</p></div>}
   {page==='sync'&&<div className="adc-page-content"><div className="adc-control-grid">{([['preCoast','Pre-coast'],['postCoast','Post-coast'],['threshold','Sync threshold']] as [AdcControlId,string][]).map(([id,label])=><Slider key={id} id={id} label={label} value={liveValues[id]} disabled={disabled} status={controlStatus(id)} syncToken={syncVersion} detail={id==='threshold'?'×200 ns':undefined} onCommit={v=>commit(id,v)}/>)}</div><p className="adc-hint">PLL divider locked: {hex(reg('01')?.value)} {hex(reg('02')?.value)}. Sync status {hex(reg('14')?.value)} · format {hex(reg('15')?.value)}.</p></div>}
   {page==='dump'&&<div className="adc-page-content adc-dump"><div className="adc-dump-tools"><span>Dump · {snapshot?.dump?.state||'not requested'}{snapshot?.dump?.received_sequences?.length?` · ${snapshot.dump.received_sequences.length}/8 frames`:''}</span><button type="button" disabled={disabled} onClick={()=>void runAction('/rnse-adc/dump')}>Dump</button><button type="button" disabled={disabled} onClick={()=>void runAction('/rnse-adc/revert')}>Revert r21</button><button type="button" disabled={disabled||!identifyAllowed} title={identifyAllowed?'Probe ID 1A and restore it to zero':'Dump first and confirm register 1D is zero'} onClick={()=>void runAction('/rnse-adc/identify')}>Identify chip</button></div><div className="adc-identification" role="status"><strong>Chip:</strong> {adcIdentificationMessage(snapshot?.identification)} <span>Restore: {snapshot?.identification?.restore_confirmed?'confirmed':snapshot?.identification?.restore?.state||'not run'}</span></div>{!identifyAllowed&&<p className="adc-hint">Dump first; identification is allowed only when register 1D reads 0x00.</p>}<div className="adc-registers" role="table" aria-label="39 ADC registers"><div className="adc-register-row adc-register-head" role="row"><span>Reg</span><span>Current</span><span>Baseline</span><span>Status</span></div>{(snapshot?.registers||[]).map(item=><div className={`adc-register-row ${item.changed?'changed':''} ${item.failed?'failed':''}`} role="row" key={item.register}><span>{item.register.toUpperCase()}</span><span>{hex(item.value)}</span><span>{hex(item.baseline)}</span><span>{item.failed?'Read failed':adcWriteMessage(snapshot,item.register.toUpperCase())||(item.changed?'Changed':'—')}</span></div>)}</div><div className="adc-preset-tools"><TouchTextInput value={presetName} onValueChange={setPresetName} aria-label="Preset name" placeholder="Preset name" maxLength={40} disabled={disabled}/><button type="button" disabled={disabled||!presetName.trim()} onClick={()=>void savePreset()}>Save preset</button><select aria-label="Saved ADC preset" value={selected} disabled={disabled} onChange={e=>setSelected(e.target.value)}><option value="">Choose preset</option>{Object.keys(presets).map(name=><option key={name}>{name}</option>)}</select><button type="button" disabled={disabled||!selected} onClick={loadPreset}>Load</button></div><p className="adc-hint">The first completed dump sets the comparison baseline.</p></div>}
 </section>;
}
function liveValuesToBytes(values:Record<AdcControlId,number>):AdcPreset {const result:AdcPreset={};for(const id of Object.keys(caps) as AdcControlId[]){if(id==='vcoRange'||id==='vcoCurrent')continue;const encoded=encodeAdcControl(id,values[id]);result[encoded.register]=encoded.byte;}result['03']=encodeVco(values.vcoRange,values.vcoCurrent);return result;}
