import { TouchTextInput } from '../components/touchKeyboard/TouchTextInput';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Socket } from 'socket.io-client';
import { DataStore } from '../store/DataStore';
import { useDataLogs } from '../hooks/useDataLogs';
import { DISIcon, Icon, iconLabel, slotIcons } from '../components/dataLogs/Icons';
import { ValuePicker } from '../components/dataLogs/ValuePicker';
import { LogReview } from '../components/dataLogs/LogReview';
import { CatalogValue, clock, DISPage, DISSlot, iconFor, LogConfig, LogProfile, LogReview as ReviewData, profileRequests, unitOptions, unitText, valueId, ValueRequest } from '../components/dataLogs/model';
import { VehicleValue } from '../types';
import '../components/dataLogs/dataLogs.css';

function Reading({ entry }: { entry: CatalogValue }) {
  const [sample, setSample] = useState<VehicleValue | undefined>(() => DataStore.getValue(entry.id));
  useEffect(() => DataStore.subscribeValue(`value:${entry.id}`, 0, () => setSample(DataStore.getValue(entry.id))), [entry.id]);
  const valid = sample?.status === 'ok' && sample.value !== null;
  const value = valid ? typeof sample.value === 'number' ? sample.value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(sample.value) : '—';
  return <div className={`dl-reading ${valid ? '' : 'unavailable'}`} title={sample?.quality.reason || entry.note || entry.id}><Icon name={iconFor(entry.id)} size={22} /><span className="dl-fill"><strong>{entry.label}</strong><small>{sample?.status || 'Waiting'}{sample?.quality.estimated ? ' · estimated' : ''}</small></span><code>{value}</code><small className="dl-reading-unit">{unitText(sample?.unit ?? entry.unit)}</small></div>;
}
const newId = (kind: string) => `${kind}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;

export function DataLogsTab({ socket, isActive, onValues }: { socket: Socket | null; isActive: boolean; onValues: (values: ValueRequest[]) => void }) {
  const { state, error, pending, refresh, mutate, save, review } = useDataLogs(socket, isActive);
  const [section, setSection] = useState<'record' | 'review' | 'dis'>('record');
  const [profileId, setProfileId] = useState('');
  const [pageIndex, setPageIndex] = useState(0);
  const [draftPages, setDraftPages] = useState<DISPage[] | null>(null);
  const [reviewData, setReviewData] = useState<ReviewData | null>(null);
  const [picker, setPicker] = useState<'profile' | 'slot' | null>(null);
  const [slotIndex, setSlotIndex] = useState<number | null>(null);
  const [slotDraft, setSlotDraft] = useState<DISSlot | null>(null);
  const [dialog, setDialog] = useState<'profile' | 'page' | null>(null);
  const [name, setName] = useState('');
  const [isNew, setIsNew] = useState(false);
  const [estimated, setEstimated] = useState(false);
  const [unverified, setUnverified] = useState(false);
  const profiles = state?.profiles || [];
  const configuredProfile = profiles.find(p => p.id === (state?.recording.recording ? state.recording.profile_id : profileId)) || profiles[0];
  const activeSession = state?.recording.recording ? state.sessions.find(session => session.id === state.recording.session_id) : undefined;
  const profile: LogProfile | undefined = useMemo(() => activeSession ? { id: activeSession.profile_id, name: activeSession.name || configuredProfile?.name || activeSession.profile_id, values: activeSession.requests || activeSession.values } : configuredProfile, [activeSession, configuredProfile]);
  const pages = draftPages || state?.dis_pages || [];
  const page = pages[pageIndex] || pages[0];
  const catalog = state?.catalog || [];
  const catalogMap = useMemo(() => new Map(catalog.map(v => [v.id, v])), [catalog]);
  const config = useCallback((nextProfiles = profiles, nextPages = pages): LogConfig => ({ version: state?.version || 1, profiles: nextProfiles, dis_pages: nextPages, settings: state?.settings || {} }), [profiles, pages, state?.version, state?.settings]);
  const subscription = useMemo(() => profileRequests(profile), [profile]);
  useEffect(() => { onValues(section === 'record' ? subscription : []); }, [subscription, section, onValues]);
  useEffect(() => { if (!draftPages) setPageIndex(index => Math.min(index, Math.max(0, (state?.dis_pages.length || 1) - 1))); }, [state?.dis_pages, draftPages]);
  const editPage = (next: DISPage) => setDraftPages(pages.map(p => p.id === next.id ? next : p));
  const storeProfiles = async (next: LogProfile[]) => { const result = await save(config(next, state?.dis_pages || [])); if (result) { setDialog(null); setPicker(null); } return result; };
  const openProfile = (creating: boolean) => { setIsNew(creating); setName(creating ? '' : profile?.name || ''); setEstimated(profile?.allow_estimated || false); setUnverified(profile?.allow_unverified || false); setDialog('profile'); };
  const openPage = (creating: boolean) => { setIsNew(creating); setName(creating ? '' : page?.name || ''); setDialog('page'); };
  const selectSlot = (index: number) => { setSlotIndex(index); setSlotDraft({ ...page.slots[index] }); };
  const openReview = async (id: string) => { const result = await review(id); if (result) { setReviewData(result); setSection('review'); } };
  const stop = async (inspect: boolean) => { const id = state?.recording.session_id; const result = await mutate('/stop', {}); if (result && id && inspect) await openReview(id); };
  const savePageName = () => {
    if (isNew) {
      const slots = page?.slots.map(slot => ({ ...slot })) || Array.from({ length: 8 }, () => ({ value_id: catalog[0]?.id || 'engine.rpm', icon: 'auto', unit: null, precision: 0, font: 'fixed' as const }));
      setDraftPages([...pages, { id: newId('page'), name: name.trim(), profile_id: profile?.id || '', slots }]); setPageIndex(pages.length);
    } else editPage({ ...page, name: name.trim() });
    setDialog(null);
  };
  if (!state) return <section className="tab-content dl-root" onPointerDown={e => e.stopPropagation()}><div className="dl-box dl-empty">{error || 'Loading vehicle data catalog…'}<button className="dl-button" onClick={() => void refresh()}>Retry</button></div></section>;
  const recording = state.recording;
  const picked = picker === 'slot' && slotDraft ? [slotDraft.value_id] : profile?.values.map(valueId) || [];
  return <section className="tab-content dl-root" aria-label="Data and logs" onPointerDown={e => e.stopPropagation()} onPointerUp={e => e.stopPropagation()}>
    {error && <div className="dl-error" role="alert"><span className="dl-fill">{error}</span><button className="dl-button" onClick={() => void refresh()}>Retry</button></div>}
    {picker ? <ValuePicker title={picker === 'slot' ? 'Choose slot value' : 'Choose logging values'} catalog={catalog} selected={picked} single={picker === 'slot'} minSelected={1} onCancel={() => setPicker(null)} onDone={ids => {
      if (picker === 'slot' && slotDraft) { setSlotDraft({ ...slotDraft, value_id: ids[0], unit: null, icon: 'auto', allow_estimated: false, allow_unverified: false }); setPicker(null); }
      else if (profile) { const existing = new Map(profile.values.map(v => [valueId(v), v])); void storeProfiles(profiles.map(p => p.id === profile.id ? { ...p, values: ids.map(id => existing.get(id) || id) } : p)); }
    }} /> : <>
      <div className="dl-workflow"><div className="dl-segments">{([{ id: 'record', label: 'Record', icon: 'record' }, { id: 'review', label: 'Review', icon: 'chart' }, { id: 'dis', label: 'DIS pages', icon: 'pages' }] as const).map(item => <button key={item.id} className={`dl-button ${section === item.id ? 'active' : ''}`} onClick={() => setSection(item.id)}><Icon name={item.icon} size={19} />{item.label}</button>)}</div>{section === 'dis' ? <><select aria-label="DIS subpage" className="dl-select dl-fill" value={page?.id || ''} onChange={e => setPageIndex(pages.findIndex(p => p.id === e.target.value))}>{pages.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="dl-button dl-icon" aria-label="Add DIS page" onClick={() => openPage(true)}><Icon name="add" /></button></> : section === 'record' ? <><select aria-label="Logging profile" className="dl-select dl-fill" value={profile?.id || ''} onChange={e => setProfileId(e.target.value)} disabled={recording.recording}>{profiles.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="dl-button dl-icon" aria-label="Add logging profile" disabled={pending} onClick={() => openProfile(true)}><Icon name="add" /></button></> : <select aria-label="Saved recording" className="dl-select dl-fill" value={reviewData?.session.id || ''} onChange={e => { if (e.target.value) void openReview(e.target.value); }}><option value="">Choose a recording</option>{state.sessions.map(session => <option key={session.id} value={session.id}>{session.name || profiles.find(p => p.id === session.profile_id)?.name || session.profile_id} · {new Date(session.started_at * 1000).toLocaleString()} · {clock(session.duration_sec)}</option>)}</select>}{section === 'review' && reviewData && <a className="dl-button" aria-label="Export recording CSV" href={`/api/data-logs/sessions/${encodeURIComponent(reviewData.session.id)}/export`} download>CSV</a>}</div>
      {section === 'record' && <><div className="dl-box dl-record-body"><div className="dl-record-header"><strong>{profile?.name || 'Create a logging profile'}</strong><small>{profile?.values.length || 0} selected values · live source status</small><button className="dl-button" disabled={!profile || pending || recording.recording} onClick={() => openProfile(false)}>Profile settings</button></div><div className="dl-readings pretty-scroll">{profile?.values.length ? profile.values.map(request => { const id = valueId(request); const entry = catalogMap.get(id); return entry ? <Reading key={id} entry={entry} /> : <div className="dl-reading" key={id}>{id} · Not in current catalog</div>; }) : <div className="dl-empty">Choose values to display and log</div>}</div></div><div className="dl-footer">{!recording.recording && <button className="dl-button" disabled={!profile || pending} onClick={() => setPicker('profile')}>Choose values</button>}<div className="dl-fill dl-status"><strong>{recording.recording ? `Recording · ${clock(recording.elapsed_sec)}` : 'Ready to record'}</strong><small>{recording.recording ? `${recording.samples} samples · ${recording.markers} markers${recording.dropped_rows ? ` · ${recording.dropped_rows} dropped rows` : ''}` : `${state.sessions.length} saved recordings`}</small></div><button className="dl-button" disabled={!recording.recording || pending} onClick={() => void mutate('/marker', { note: 'Driver marker' })}><Icon name="marker" />Mark</button>{recording.recording && <button className="dl-button" disabled={pending} onClick={() => void stop(true)}>Stop & review</button>}<button className="dl-button dl-primary" disabled={pending || (!recording.recording && !profile?.values.length)} onClick={() => recording.recording ? void stop(false) : void mutate('/start', { profile_id: profile?.id })}><Icon name={recording.recording ? 'stop' : 'record'} />{recording.recording ? 'Stop & save' : 'Start'}</button></div></>}
      {section === 'review' && (reviewData ? <><LogReview key={reviewData.session.id} data={reviewData} catalog={reviewData.session.catalog || catalog} onRange={async (range) => { const result = await review(reviewData.session.id, range); if (result) setReviewData(result); }} /></> : <div className="dl-box dl-empty">{state.sessions.length ? 'Choose a saved recording above to graph and inspect' : 'Start a recording, then stop to review it here'}</div>)}
      {section === 'dis' && <>{page ? <div className="dl-box dl-slots">{page.slots.map((slot, index) => <button key={index} className="dl-slot" onClick={() => selectSlot(index)}><span className="dl-slot-index">{Math.floor(index / 2) + 1}{index % 2 ? 'R' : 'L'}</span><DISIcon name={slot.icon === 'auto' ? iconFor(slot.value_id) : slot.icon} /><span className="dl-fill"><strong>{catalogMap.get(slot.value_id)?.label || slot.value_id}</strong><small>{unitText(slot.unit ?? catalogMap.get(slot.value_id)?.unit) || (catalogMap.get(slot.value_id)?.unit_policy === 'reported' ? 'ECU unit' : 'Unitless')} · {slot.font === 'fixed' ? 'Fixed' : 'Proportional'} · {slot.precision} decimals</small></span><Icon name="chevron" size={18} /></button>)}</div> : <div className="dl-box dl-empty">Add a DIS page to choose eight readings</div>}<div className="dl-footer"><div className="dl-fill dl-status"><strong>{page?.name || 'DIS pages'}</strong><small>{draftPages ? 'Unapplied changes' : 'Configuration saved'}</small></div><select aria-label="Linked DIS logging profile" className="dl-select" disabled={!page} value={page?.profile_id || ''} onChange={e => editPage({ ...page, profile_id: e.target.value })}>{profiles.map(p => <option key={p.id} value={p.id}>Log: {p.name}</option>)}</select><button className="dl-button" disabled={!page} onClick={() => openPage(false)}>Page settings</button><button className="dl-button dl-primary" disabled={!draftPages || pending} onClick={async () => { if (await save(config())) setDraftPages(null); }}><Icon name="check" />Apply</button></div></>}
    </>}
    {!picker && slotDraft && <div className="dl-modal-shade" role="presentation"><div className="dl-dialog dl-slot-dialog" role="dialog" aria-modal="true" aria-label="Configure DIS slot"><div className="dl-dialog-title"><h2>Slot {Math.floor((slotIndex || 0) / 2) + 1}{(slotIndex || 0) % 2 ? 'R' : 'L'}</h2><button className="dl-button" onClick={() => setSlotDraft(null)}>Cancel</button><button className="dl-button dl-primary" onClick={() => { if (slotIndex !== null) editPage({ ...page, slots: page.slots.map((slot, index) => index === slotIndex ? slotDraft : slot) }); setSlotDraft(null); }}>Done</button></div><button className="dl-button dl-slot-value" onClick={() => setPicker('slot')}><Icon name={iconFor(slotDraft.value_id)} /><span className="dl-fill">{catalogMap.get(slotDraft.value_id)?.label || slotDraft.value_id}</span><Icon name="chevron" /></button><div className="dl-field-grid"><label>Units<select className="dl-select" value={slotDraft.unit ?? ''} onChange={e => setSlotDraft({ ...slotDraft, unit: e.target.value || null })}><option value="">Source unit{catalogMap.get(slotDraft.value_id)?.unit ? ` · ${unitText(catalogMap.get(slotDraft.value_id)?.unit)}` : ''}</option>{unitOptions(catalogMap.get(slotDraft.value_id)?.unit || null).filter(Boolean).map(unit => <option key={unit} value={unit}>{unitText(unit) || (catalogMap.get(slotDraft.value_id)?.unit_policy === 'reported' ? 'ECU reported unit' : 'Unitless')}</option>)}</select></label><label>Decimals<select className="dl-select" value={slotDraft.precision} onChange={e => setSlotDraft({ ...slotDraft, precision: Number(e.target.value) })}>{[0, 1, 2, 3].map(n => <option key={n}>{n}</option>)}</select></label><label>Native text font<select className="dl-select" value={slotDraft.font} onChange={e => setSlotDraft({ ...slotDraft, font: e.target.value as DISSlot['font'] })}><option value="fixed">Fixed width</option><option value="proportional">Proportional</option></select></label></div><div className="dl-slot-policy">{catalogMap.get(slotDraft.value_id)?.providers.some(p => p.estimated) && <label className="dl-checkbox"><input type="checkbox" checked={slotDraft.allow_estimated || false} onChange={e => setSlotDraft({ ...slotDraft, allow_estimated: e.target.checked })} />Allow estimated providers</label>}{catalogMap.get(slotDraft.value_id)?.providers.some(p => !p.verified) && <label className="dl-checkbox"><input type="checkbox" checked={slotDraft.allow_unverified || false} onChange={e => setSlotDraft({ ...slotDraft, allow_unverified: e.target.checked })} />Allow unverified providers</label>}</div><div className="dl-icon-choices pretty-scroll" aria-label="DIS icon">{slotIcons.map(icon => <button key={icon} className={`dl-button ${slotDraft.icon === icon ? 'active' : ''}`} onClick={() => setSlotDraft({ ...slotDraft, icon })}><DISIcon name={icon === 'auto' ? iconFor(slotDraft.value_id) : icon} /><small>{iconLabel(icon)}</small></button>)}</div></div></div>}
    {!picker && dialog && <div className="dl-modal-shade"><div className="dl-dialog" role="dialog" aria-modal="true" aria-label={dialog === 'profile' ? 'Logging profile settings' : 'DIS page settings'}><h2>{isNew ? 'New' : 'Edit'} {dialog === 'profile' ? 'logging profile' : 'DIS page'}</h2><label>Name<TouchTextInput aria-label={dialog === 'profile' ? 'Logging profile name' : 'DIS page name'} value={name} maxLength={dialog === 'page' ? 12 : 48} onValueChange={setName} capitalize autoFocus /></label>{dialog === 'profile' ? <><label className="dl-checkbox"><input type="checkbox" checked={estimated} onChange={e => setEstimated(e.target.checked)} />Allow estimated providers</label><label className="dl-checkbox"><input type="checkbox" checked={unverified} onChange={e => setUnverified(e.target.checked)} />Allow unverified providers</label></> : !isNew && <div className="dl-page-actions"><button className="dl-button" disabled={pageIndex === 0} onClick={() => { const next = [...pages]; [next[pageIndex - 1], next[pageIndex]] = [next[pageIndex], next[pageIndex - 1]]; setDraftPages(next); setPageIndex(pageIndex - 1); }}>Move earlier</button><button className="dl-button" disabled={pageIndex >= pages.length - 1} onClick={() => { const next = [...pages]; [next[pageIndex], next[pageIndex + 1]] = [next[pageIndex + 1], next[pageIndex]]; setDraftPages(next); setPageIndex(pageIndex + 1); }}>Move later</button><button className="dl-button" onClick={() => { const next = { ...page, id: newId('page'), name: `${page.name.slice(0, 8)} copy`, slots: page.slots.map(s => ({ ...s })) }; setDraftPages([...pages, next]); setPageIndex(pages.length); setDialog(null); }}>Duplicate</button></div>}<div className="dl-dialog-actions"><button className="dl-button" onClick={() => setDialog(null)}>Cancel</button><button className="dl-button dl-primary" disabled={!name.trim() || pending} onClick={() => { if (dialog === 'page') savePageName(); else { const next = { ...(isNew ? { id: newId('profile'), values: profile?.values.map(v => typeof v === 'string' ? v : { ...v }) || ['engine.rpm'] } : profile), name: name.trim(), allow_estimated: estimated, allow_unverified: unverified }; void storeProfiles(isNew ? [...profiles, next] : profiles.map(p => p.id === next.id ? next : p)).then(saved => { if (saved) setProfileId(next.id); }); } }}>Save</button></div></div></div>}
  </section>;
}
