"""Export the production DIS pixel icons and automatic choices for DataView.

Run after editing readings_assets.py so the picker shows the actual LCD artwork.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from dis_client.readings_assets import ICONS, ICON_TERMS


def pixel_path(rows):
    return ''.join(f'M{x} {y}h1v1h-1z' for y, row in enumerate(rows)
                   for x, bit in enumerate(row) if bit == '1')


def export():
    icons = {name: {'height': len(rows), 'path': pixel_path(rows)}
             for name, rows in ICONS.items()}
    output = '// Generated by tools/export_dis_reading_assets.py; edit the DIS source artwork.\n'
    output += 'export const disIconPixels: Record<string, { height: number; path: string }> = '
    output += json.dumps(icons, ensure_ascii=False, separators=(',', ':')) + ';\n'
    output += 'export const disIconTerms: Array<[string, string]> = '
    output += json.dumps(ICON_TERMS, ensure_ascii=False, separators=(',', ':')) + ';\n'
    target = ROOT / 'hudiy_dataview/src/components/dataLogs/disPixelAssets.ts'
    target.write_text(output, encoding='utf8')
    print(f'Exported {len(icons)} DIS icon choices and {len(ICON_TERMS)} automatic rules')


if __name__ == '__main__':
    export()
