#!/usr/bin/env python3
"""Export the actual value catalog and its reference audit without hardware."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from vehicle_data.catalog import CATALOG, get_catalog, get_catalog_coverage
from vehicle_data.engine_definitions import coverage_ledger


def markdown():
    coverage = get_catalog_coverage()
    engine = coverage['engine_reference']
    lines = ['# Vehicle value catalog', '',
        'Generated by `python3 tools/export_value_catalog.py --format markdown`.', '',
        f"{coverage['value_count']} canonical values; {coverage['provider_count']} providers.", '',
        f"Engine reference: {engine['supported_count']}/{engine['meaningful_count']} labeled field occurrences mapped; "
        f"{engine['placeholder_count']} blank placeholders excluded. Repeated fields are alternate providers, not extra values.", '',
        'Mappings are documented in the supplied references, not independently validated on every ECU. '
        'Unknown formulas still yield invalid samples. Identification entries expose individual decoded fields; '
        'they do not assemble a complete VIN. Unconfirmed extra fields require explicit opt-in.', '',
        '`reported` means the reference does not fix a unit: the sample retains the ECU-decoded unit. '
        'Status fields preserve numeric codes or text; bitfields preserve masked bits without inventing their meanings.', '',
        '`estimated` providers require `allow_estimated: true`; `unverified` providers require `allow_unverified: true`.', '',
        'The complete provider mappings and engine coverage ledger are available with `--format json`.', '',
        '| ID | Label | Unit | Type | Providers |', '| --- | --- | --- | --- | --- |']
    for value_id, entry in sorted(CATALOG.items()):
        sources = []
        for provider in entry['providers']:
            source = (f"ICAN 0x{provider['can_id']:03X}" if provider['kind'] == 'ican'
                      else f"Diag {provider['module']:02X}")
            if provider.get('estimated'):
                source += ' estimated'
            if not provider.get('verified'):
                source += ' unverified'
            sources.append(source)
        sources = ', '.join(sorted(set(sources)))
        unit = 'reported' if entry.get('unit_policy') == 'reported' else entry.get('unit') or 'unitless'
        label = entry['label'].replace('|', '\\|')
        lines.append(f"| `{value_id}` | {label} | {unit} | {entry['type']} | {sources} |")
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--format', choices=('json', 'markdown'), default='json')
    parser.add_argument('--output', type=Path, help='Write output to this file instead of stdout')
    args = parser.parse_args()
    output = (markdown() if args.format == 'markdown' else json.dumps({
        'version': 1, 'coverage': get_catalog_coverage(), 'values': get_catalog(),
        'engine_fields': coverage_ledger(CATALOG)['fields'],
    }, ensure_ascii=False, indent=2, allow_nan=False) + '\n')
    if args.output:
        args.output.write_text(output, encoding='utf-8')
    else:
        sys.stdout.write(output)


if __name__ == '__main__':
    main()
